name: Copy files.json and Generate Version Info

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  copy-and-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取所有历史记录以获取完整的git信息

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Copy files.json and cursor-rules directory to web directory
      run: |
        cp files.json web/
        echo "Copied files.json to web directory"
        
        # cursor-rules 디렉토리가 존재하는 경우에만 복사
        if [ -d "cursor-rules" ]; then
          # web/cursor-rules 디렉토리가 이미 존재하면 삭제
          if [ -d "web/cursor-rules" ]; then
            rm -rf web/cursor-rules
          fi
          cp -r cursor-rules web/
          echo "Copied cursor-rules directory to web directory"
        else
          echo "cursor-rules directory not found, skipping copy"
        fi

    - name: Generate version-info.json
      run: |
        cat > web/version-info.json <<EOF
        {
          "last_commit_id": "$(git rev-parse HEAD)",
          "last_commit_message": "$(git log -1 --pretty=%B | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')",
          "branch": "${GITHUB_REF#refs/heads/}",
          "committed_at": "$(git log -1 --format=%cI)",
          "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        }
        EOF
        echo "Generated version-info.json"

    - name: Verify copied files
      run: |
        ls -l web/files.json
        if [ -d "web/cursor-rules" ]; then
          ls -l web/cursor-rules
        fi
        ls -l web/version-info.json
        echo "=== Content of version-info.json ==="
        cat web/version-info.json
        echo "===================================="

    - name: Commit and push changes (if needed)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add web/files.json web/version-info.json
        # cursor-rules 디렉토리가 존재하면 추가
        if [ -d "web/cursor-rules" ]; then
          git add web/cursor-rules
        fi
        # 检查是否有变更需要提交
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update: Copy files.json, cursor-rules and generate version info"
          git push
          echo "Changes committed and pushed"
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}