name: cursor-rules
on: [pull_request, push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make rules-merge
      - run: make rules-check
      - uses: actions/upload-artifact@v4
        with:
          name: cursor-rules-merged
          path: .cursorrules/_merged.md