name: Generate Markdown File List

on:
  push:
    branches:
      - main
    paths:
      - '.cursorrules/**'
  workflow_dispatch:

jobs:
  generate-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate file list
        run: |
          echo "현재 디렉터리: $(pwd)"
          echo "디렉터리 구조:"
          ls -la
          
          MD_DIRS=(
            ".cursorrules"
            ".cursorrules/common"
            ".cursorrules/project"
            ".cursorrules/generated"
            ".cursorrules/common/stacks"
          )
          
          # Ensure 'web' directory exists
          mkdir -p web
          
          # Initialize the JSON array file
          echo "[" > web/files.json
          
          first_file=true
          file_found=false
          
          # Loop through each directory to find .md files
          for dir in "${MD_DIRS[@]}"; do
            if [ -d "$dir" ]; then
              echo "디렉터리 존재: $dir"
              while IFS= read -r -d '' file; do
                echo "파일 찾음: $file"
                file_found=true
                
                if [ "$first_file" = false ]; then
                  echo "," >> web/files.json
                fi
                first_file=false
                
                RAW_URL="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/${file}"
                echo "{\"path\":\"$file\",\"raw_url\":\"$RAW_URL\"}" >> web/files.json
              done < <(find "$dir" -type f -name "*.md" -print0)
            else
              echo "디렉터리 없음: $dir"
            fi
          done
          
          echo "]" >> web/files.json
          
          # If no files were found, ensure the file is an empty array
          if [ "$file_found" = false ]; then
            echo "[]" > web/files.json
          fi
          
          echo "Generated files.json:"
          cat web/files.json

      - name: Commit and push changes
        run: |
          # Check for changes before committing
          git diff --quiet --exit-code web/files.json || git add web/files.json && git commit -m "Update files.json" && git push